### PR TITLE
change PUT to PATCH and only change role for user

### LINKED ISSUE #154: Change PUT to PATCH for updating users
**Describe the bug**
Currently, we are using PUT http request to update the user's role. However, the PUT request should update the entire document. We are only updating one field. Thus, we should be using PATCH. 

"The HTTP methods PATCH can be used to update partial resources. For instance, when you only need to update one field of the resource, PUTting a complete resource representation might be cumbersome and utilizes more bandwidth."

### PR DESCRIPTION
**Pull request by Polarpi**
## Status:
:construction: 

## Description
Change PUT request for users to PATCH, because it only changes one field (currently). We want it to just change the user's role.
 

Fixes #154 

## Todos
After merging #153, will also add ability to update the Title field.

### CODE REVIEW

File: backend/routes/api/users.js [hunk 1]
```diff
@@ -124,20 +124,14 @@ router.post(
   })
 );
 
-// set role
-router.put(
-  "/:user_id/role",
+// set role and title
+router.patch(
```
Comment (alan-fang) [inline backend/routes/api/users.js]: is there a way to generalize this to be able to set any arbitrary field? just wondering

Comment (josh-byster) [reply backend/routes/api/users.js]: Yes! We actually just removed that functionality since Eugenia and I discussed how we'll probably never have to change something like first name or last name since that's coming from Google OAuth, but we could absolutely keep in that functionality if you think it's better to support that.
